name: AUR Releaser
description: Publish new release of an AUR by updating its version or number
branding:
  color: green
  icon: upload
inputs:
  package_name:
    description: Name of the package to publish
    required: true
  package_version:
    description: Version of the package to publish
    required: false
  package_type:
    description: Type of the package to publish
    required: false
    default: stable
  commit_message:
    description: Message to use when commiting
    required: false
    default: Update to ${package_version}
  aur_private_key:
    description: SSH private key with write permissions to AUR Git
    required: true
  aur_username:
    description: Username to configure the AUR Git with
    required: true
  aur_email:
    description: Email to configure the AUR Git with
    required: true
  skip_test:
    description: Flag if testing has to be skipped
    required: false
    default: no
runs:
  using: docker
  image: Dockerfile
